# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grid_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *




class Ui_MainWindow(QMainWindow):
    def __init__(self, parent=None):
        super(Ui_MainWindow, self).__init__()
        self.textColor = "#FEE715"
        self.tileColor = "#1a1a1c"
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 94)

        MainWindow.setWindowFlags(Qt.FramelessWindowHint)
        MainWindow.setAttribute(Qt.WA_TranslucentBackground, True)
        MainWindow.setWindowFlag(Qt.Tool)

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: transparent;")
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QRect(0, 0, 431, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QFrame(self.verticalLayoutWidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: "+self.tileColor+";\n"
"color:"+self.textColor+";\n"
"font: 28px \"Franklin Gothic Book\";\n"
"};\n"
"")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_6 = QPushButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 6, 0, 1, 3)
        self.darkButton = QPushButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.darkButton.sizePolicy().hasHeightForWidth())
        self.darkButton.setSizePolicy(sizePolicy)
        self.darkButton.setObjectName("darkButton")
        self.gridLayout.addWidget(self.darkButton, 7, 0, 1, 1)
        self.lightButton = QPushButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lightButton.sizePolicy().hasHeightForWidth())
        self.lightButton.setSizePolicy(sizePolicy)
        self.lightButton.setObjectName("lightButton")
        self.gridLayout.addWidget(self.lightButton, 7, 1, 1, 1)
        self.solarButton = QPushButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solarButton.sizePolicy().hasHeightForWidth())
        self.solarButton.setSizePolicy(sizePolicy)
        self.solarButton.setObjectName("solarButton")
        self.gridLayout.addWidget(self.solarButton, 7, 2, 1, 1)
        self._2pomodoroButton = QPushButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._2pomodoroButton.sizePolicy().hasHeightForWidth())
        self._2pomodoroButton.setSizePolicy(sizePolicy)
        self._2pomodoroButton.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self._2pomodoroButton, 3, 0, 1, 3)
        self.frame_2 = QFrame(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("border-radius: 20px;background-color: "+self.tileColor+";color:"+self.textColor+";\n"
"font: 28pt \"Glacial Indifference\";")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnResizeWindow = QPushButton(self.frame_2)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResizeWindow.sizePolicy().hasHeightForWidth())
        self.btnResizeWindow.setSizePolicy(sizePolicy)
        self.btnResizeWindow.setText("")
        icon = QIcon()
        icon.addPixmap(QPixmap("images/menu.png"), QIcon.Normal, QIcon.Off)
        self.btnResizeWindow.setIcon(icon)
        self.btnResizeWindow.setIconSize(QSize(30, 30))
        self.btnResizeWindow.setObjectName("btnResizeWindow")
        self.horizontalLayout.addWidget(self.btnResizeWindow)
        self.label = QLabel(self.frame_2)
        self.label.setStyleSheet("border-radius: 20px;background-color: "+self.tileColor+";color:"+self.textColor+";\n"
"font: 22pt \"Glacial Indifference\";")
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.exitButton = QPushButton(self.frame_2)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setText("")
        icon1 = QIcon()
        icon1.addPixmap(QPixmap("images/cancel.png"), QIcon.Normal, QIcon.Off)
        self.exitButton.setIcon(icon1)
        self.exitButton.setIconSize(QSize(30, 30))
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 3)
        spacerItem = QSpacerItem(1, 1, QSizePolicy.Minimum, QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_5 = QPushButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 5, 0, 1, 3)
        self.pushButton_4 = QPushButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 4, 0, 1, 3)
        self._1todolistButton = QPushButton(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._1todolistButton.sizePolicy().hasHeightForWidth())
        self._1todolistButton.setSizePolicy(sizePolicy)
        self._1todolistButton.setStyleSheet("border-radius: 20px;\n"
"background-color: "+self.tileColor+";\n"
"color:"+self.textColor+";\n"
"font: 28px \"Franklin Gothic Book\";")
        self._1todolistButton.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self._1todolistButton, 2, 0, 1, 3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)
        

        
    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setText(_translate("MainWindow", "Calculator"))
        self.darkButton.setText(_translate("MainWindow", "Dark"))
        self.lightButton.setText(_translate("MainWindow", "Light"))
        self.solarButton.setText(_translate("MainWindow", "Solar"))
        self._2pomodoroButton.setText(_translate("MainWindow", "Pomodoro"))
        self.label.setText(_translate("MainWindow", "RoteReaf"))
        self.pushButton_5.setText(_translate("MainWindow", "Wikipedia"))
        self.pushButton_4.setText(_translate("MainWindow", "Translation"))
        self._1todolistButton.setText(_translate("MainWindow", "Todo List"))


class Ui_TodoList(QMainWindow):
    def __init__(self, parent=None):
        super(Ui_TodoList, self).__init__()
        self.textColor = "#FEE715"
        self.tileColor = "#1a1a1c"
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 94)

        MainWindow.setWindowFlags(Qt.FramelessWindowHint)
        MainWindow.setAttribute(Qt.WA_TranslucentBackground, True)
        MainWindow.setWindowFlag(Qt.Tool)

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
"QPushButton{\n"
"border-radius: 20px;\n"
"background-color: "+self.tileColor+";\n"
"color:"+self.textColor+";\n"
"font: 28px \"Franklin Gothic Book\";\n"
"};\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.addItem = QPushButton(self.centralwidget)
        self.addItem.setGeometry(QRect(20, 100, 381, 71))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addItem.sizePolicy().hasHeightForWidth())
        self.addItem.setSizePolicy(sizePolicy)
        self.addItem.setObjectName("addItem")
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setGeometry(QRect(10, 10, 401, 75))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("border-radius: 20px;background-color: "+self.tileColor+";color:"+self.textColor+";\n"
"font: 28pt \"Glacial Indifference\";")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnResizeWindow = QPushButton(self.frame_3)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResizeWindow.sizePolicy().hasHeightForWidth())
        self.btnResizeWindow.setSizePolicy(sizePolicy)
        self.btnResizeWindow.setText("")
        icon = QIcon()
        icon.addPixmap(QPixmap("images/menu.png"), QIcon.Normal, QIcon.Off)
        self.btnResizeWindow.setIcon(icon)
        self.btnResizeWindow.setIconSize(QSize(30, 30))
        self.btnResizeWindow.setObjectName("btnResizeWindow")
        self.horizontalLayout_3.addWidget(self.btnResizeWindow)
        self.label_3 = QLabel(self.frame_3)
        self.label_3.setStyleSheet("border-radius: 20px;background-color: "+self.tileColor+";color:"+self.textColor+";\n"
"font: 22pt \"Glacial Indifference\";")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.exitButton = QPushButton(self.frame_3)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setText("")
        icon1 = QIcon()
        icon1.addPixmap(QPixmap("images/cancel.png"), QIcon.Normal, QIcon.Off)
        self.exitButton.setIcon(icon1)
        self.exitButton.setIconSize(QSize(30, 30))
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_3.addWidget(self.exitButton)
        
        self.backButton = QPushButton(self.centralwidget)
        self.backButton.setGeometry(QRect(20, 450, 381, 71))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setObjectName("backButton")
        self.darkButton = QPushButton(self.centralwidget)
        self.darkButton.setGeometry(QRect(10, 530, 131, 71))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.darkButton.sizePolicy().hasHeightForWidth())
        self.darkButton.setSizePolicy(sizePolicy)
        self.darkButton.setStyleSheet("border-radius: 20px;\n"
"font: 28px \"Franklin Gothic Book\";")
        self.darkButton.setObjectName("darkButton")
        self.lightButton = QPushButton(self.centralwidget)
        self.lightButton.setGeometry(QRect(150, 530, 121, 71))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lightButton.sizePolicy().hasHeightForWidth())
        self.lightButton.setSizePolicy(sizePolicy)
        self.lightButton.setStyleSheet("border-radius: 20px;\n"
"font: 28px \"Franklin Gothic Book\";")
        self.lightButton.setObjectName("lightButton")
        self.solarButton = QPushButton(self.centralwidget)
        self.solarButton.setGeometry(QRect(280, 530, 131, 71))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solarButton.sizePolicy().hasHeightForWidth())
        self.solarButton.setSizePolicy(sizePolicy)
        self.solarButton.setStyleSheet("border-radius: 20px;\n"
"font: 28px \"Franklin Gothic Book\";")
        self.solarButton.setObjectName("solarButton")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QRect(20, 180, 381, 261))
        self.scrollArea.setStyleSheet("border:none; background: transparent;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 360, 1612))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.darkButton.clicked.connect(lambda:self.theme('dark'))
        self.lightButton.clicked.connect(lambda:self.theme('light'))
        self.solarButton.clicked.connect(lambda:self.theme('solar'))

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def myStyleSheet(self):
        self.centralwidget.setStyleSheet("\n"
"QPushButton{\n"
"border-radius: 20px;\n"
"background-color: "+self.tileColor+";\n"
"color:"+self.textColor+";\n"
"font: 28px \"Franklin Gothic Book\";\n"
"};\n"
"")
        self.frame_3.setStyleSheet("border-radius: 20px;background-color: "+self.tileColor+";color:"+self.textColor+";\n"
"font: 28pt \"Glacial Indifference\";")

        self.label_3.setStyleSheet("border-radius: 20px;background-color: "+self.tileColor+";color:"+self.textColor+";\n"
"font: 22pt \"Glacial Indifference\";")

        

    def theme(self,t):
        if t=='dark':
            self.textColor = '#FEE715'
            self.tileColor = '#1a1a1c'
        if t=='light':
            self.textColor = '#2BAE66'
            self.tileColor = '#FCF6F5'
        self.myStyleSheet()
        self.update()

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addItem.setText(_translate("MainWindow", "Add Item"))
        self.backButton.setText(_translate("MainWindow", "<= Back"))
        self.label_3.setText(_translate("MainWindow", "TodoList"))
        self.darkButton.setText(_translate("MainWindow", "Dark"))
        self.lightButton.setText(_translate("MainWindow", "Light"))
        self.solarButton.setText(_translate("MainWindow", "Solar"))



if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    widget = QStackedWidget()
    MainWindow = QMainWindow()
    w = Ui_MainWindow()
    widget.addWidget(w)
    sys.exit(app.exec_())
